# Site settings
title: Soil Classification Tool
email: your-email@example.com
description: >- # this means to ignore newlines until "baseurl:"
  This is a soil classification tool based on the ASTM D2487 standard.
baseurl: "/soil-classification-tool-d2487" # the subpath of your site, e.g. /blog
url: "https://borczeangelov.github.io" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: jekyllrb
github_username:  jekyll

# Build settings
theme: jekyll-theme-minimal
plugins:
  - jekyll-feed
